# Generated by Django 4.1 on 2022-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='name',
            field=models.CharField(choices=[('PERSON', 'Person'), ('CAR', 'Car')], max_length=255),
        ),
    ]
