# Generated by Django 4.1 on 2022-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_nodetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
