# Generated by Django 4.1 on 2022-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_nodetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
