# Generated by Django 4.1 on 2022-08-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_nodetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
