# Generated by Django 4.1 on 2022-08-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_node_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
