version: '3'

services:
  db:
    container_name: relnod_db_postgres
    image: postgres
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=relnod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    container_name: relnod_app
    build: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../backend/relnod:/code
    ports:
      - "8000:8000"
  node:
    container_name: relnod_node
    build: node
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/usr/src/node
    command: bash /usr/src/node/run.sh
